name: Java Build

on:
  push:
    branches:
      - master
      - "release/*"
  pull_request:

jobs:
  Build-Artifacts:
    runs-on: linux-amd64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "maven"

      - name: Build artifacts with Maven
        run: mvn clean install -Dgpg.passphrase="${{ secrets.GPG_PASS }}" -Dsign=true
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: Publish artifacts
        run: mvn deploy
        env:
          MAVEN_OPTS: "-Xmx128m"

      - name: Archive job artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            target/*pom
            target/*jar
            target/*asc
